{{- $existing := lookup "v1" "Secret" .Release.Namespace (include "grafana.secretName" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grafana.secretName" . }}
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  {{- if $existing }}
  GRAFANA_ADMIN_PASSWORD: {{ index $existing.data "GRAFANA_ADMIN_PASSWORD" }}
  {{- else }}
  GRAFANA_ADMIN_PASSWORD: {{ (.Values.auth.adminPassword | default (randAlphaNum 16)) | b64enc }}
  {{- end }}
