apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  labels:
    {{- include "jaeger.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "jaeger.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "jaeger.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: jaeger
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.ports.ui }}
              name: ui
              protocol: TCP
            - containerPort: {{ .Values.ports.otlpGrpc }}
              name: otlp-grpc
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /status
              port: 13133
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /status
              port: 13133
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
