apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: jaeger-allow-ingress
  labels:
    {{- include "jaeger.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "jaeger.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector: {}
      ports:
        - port: {{ .Values.ports.ui }}
          protocol: TCP
        - port: {{ .Values.ports.otlpGrpc }}
          protocol: TCP
