{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: jaeger
  labels:
    {{- include "jaeger.labels" . | nindent 4 }}
spec:
  to:
    kind: Service
    name: jaeger
    weight: 100
  port:
    targetPort: ui
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
{{- end }}
