apiVersion: v1
kind: Service
metadata:
  name: jaeger
  labels:
    {{- include "jaeger.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.ports.ui }}
      targetPort: {{ .Values.ports.ui }}
      name: ui
    - port: {{ .Values.ports.otlpGrpc }}
      targetPort: {{ .Values.ports.otlpGrpc }}
      name: otlp-grpc
  selector:
    {{- include "jaeger.selectorLabels" . | nindent 4 }}
