apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  labels:
    {{- include "otel-collector.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "otel-collector.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "otel-collector.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: otel-collector
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --config=/etc/otelcol/config.yaml
          ports:
            - containerPort: {{ .Values.ports.otlpGrpc }}
              name: otlp-grpc
              protocol: TCP
            - containerPort: {{ .Values.ports.otlpHttp }}
              name: otlp-http
              protocol: TCP
            - containerPort: {{ .Values.global.otelCollectorPrometheusPort }}
              name: prometheus
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/otelcol
          livenessProbe:
            httpGet:
              path: /
              port: 13133
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: 13133
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
      volumes:
        - name: config
          configMap:
            name: otel-collector-config
