image:
  repository: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib
  tag: 0.153.0
  pullPolicy: IfNotPresent

ports:
  otlpGrpc: 4317
  otlpHttp: 4318

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "250m"
