apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: ogx
        static_configs:
          - targets: ['otel-collector:{{ .Values.global.otelCollectorPrometheusPort }}']
